# Generated by Django 6.0.4 on 2026-05-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="total_revenue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
