# Generated by Django 6.0.4 on 2026-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CampusZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("HOSTEL", "Hostel"),
                            ("DEPT", "Department"),
                            ("ACADEMIC", "Academic Building"),
                            ("COMMON", "Common Area"),
                        ],
                        default="COMMON",
                        max_length=20,
                    ),
                ),
                (
                    "address_keywords",
                    models.TextField(
                        help_text="Comma-separated keywords to match delivery addresses"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
